App\Form\Model\ProductDto:
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 3
          max: 255
          minMessage: 'Product name must be al least {{ limit }} characters long'
          maxMessage: 'Product name cannot be longer than {{ limit }} characters'
    description:
      - NotBlank: ~
      - Length:
          min: 3
          max: 255
          minMessage: 'Product description name must be al least {{ limit }} characters long'
          maxMessage: 'Product description name cannot be longer than {{ limit }} characters'
    price:
#      - Positive: ~
      - NotBlank: ~
    enabled:
#      - Type: bool
      - NotBlank: ~
    category:
      - NotBlank: ~
    base64Image:
#      - NotBlank: ~